services:
  postgres:
    volumes:
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d:ro

  sqitch:
    volumes:
      - ./migrations:/repo
      - ./migrations:/repo

  caddy:
    volumes:
      - ./caddy/conf:/etc/caddy
    environment:
      - CADDY_AUTO_HTTPS=off
