services:
  postgres:
    volumes:
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d:ro

  sqitch:
    working_dir: /data
    volumes:
      - ./migrations:/workspace

  caddy:
    volumes:
      - ./caddy/conf:/etc/caddy
    environment:
      - CADDY_AUTO_HTTPS=off
